name: Guardian Audit & Tests

on:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  test-and-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest requests

      - name: Run tests
        run: |
          PYTHONPATH=$PWD/src python -m pytest -q

      - name: Run static scan
        run: |
          python scripts/run_scan.py
